[package]
name = "prepare_commit_message"
version = "0.1.0"
authors = ["Phung Nguyen <longphung.nn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.3"
